import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "../components/sonner";

export const metadata: Metadata = {
  title: "Newi",
  description: "Generated by Frahn7",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
